name: Build and Test

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
    debug-ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v1
            - name: Build and Test
              run: |
                docker build -t hetnetdb:${GITHUB_SHA} .
                docker rmi hetnetdb:${GITHUB_SHA}
  scc_job:
    runs-on: ubuntu-latest
    name: A code counter with complexity calculations and COCOMO estimates.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the lines of code.
        id: scc
        uses: iryanbell/scc-docker-action@v1.0.0
        with:
          args: ${{ env.workspace }}
