on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
    debug-ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v1
            - name: Build and Test
              run: |
                docker build -t hetnetdb:${GITHUB_SHA} .
                docker rmi hetnetdb:${GITHUB_SHA}
